// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/GoYoko/web"
	"github.com/chaitin/MonkeyCode/backend/config"
	"github.com/chaitin/MonkeyCode/backend/internal/scanner/handler/http/v1"
	"github.com/chaitin/MonkeyCode/backend/pkg/logger"
	"github.com/chaitin/MonkeyCode/backend/pkg/version"
	"log/slog"
)

// Injectors from wire.go:

func newServer() (*Server, error) {
	configConfig, err := config.Init()
	if err != nil {
		return nil, err
	}
	web := NewWeb(configConfig)
	loggerConfig := configConfig.Logger
	slogLogger := logger.NewLogger(loggerConfig)
	scannerHandler := v1.NewScannerHandler(web, slogLogger)
	versionInfo := version.NewVersionInfo()
	server := &Server{
		web:     web,
		config:  configConfig,
		logger:  slogLogger,
		handler: scannerHandler,
		version: versionInfo,
	}
	return server, nil
}

// wire.go:

type Server struct {
	web     *web.Web
	config  *config.Config
	logger  *slog.Logger
	handler *v1.ScannerHandler
	version *version.VersionInfo
}
