// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// AdminLoginHistory is the predicate function for adminloginhistory builders.
type AdminLoginHistory func(*sql.Selector)

// AdminRole is the predicate function for adminrole builders.
type AdminRole func(*sql.Selector)

// ApiKey is the predicate function for apikey builders.
type ApiKey func(*sql.Selector)

// BillingPlan is the predicate function for billingplan builders.
type BillingPlan func(*sql.Selector)

// BillingQuota is the predicate function for billingquota builders.
type BillingQuota func(*sql.Selector)

// BillingRecord is the predicate function for billingrecord builders.
type BillingRecord func(*sql.Selector)

// BillingUsage is the predicate function for billingusage builders.
type BillingUsage func(*sql.Selector)

// CodeSnippet is the predicate function for codesnippet builders.
type CodeSnippet func(*sql.Selector)

// Extension is the predicate function for extension builders.
type Extension func(*sql.Selector)

// InviteCode is the predicate function for invitecode builders.
type InviteCode func(*sql.Selector)

// License is the predicate function for license builders.
type License func(*sql.Selector)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// ModelProvider is the predicate function for modelprovider builders.
type ModelProvider func(*sql.Selector)

// ModelProviderModel is the predicate function for modelprovidermodel builders.
type ModelProviderModel func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// SecurityScanning is the predicate function for securityscanning builders.
type SecurityScanning func(*sql.Selector)

// SecurityScanningResult is the predicate function for securityscanningresult builders.
type SecurityScanningResult func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskRecord is the predicate function for taskrecord builders.
type TaskRecord func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserGroup is the predicate function for usergroup builders.
type UserGroup func(*sql.Selector)

// UserGroupAdmin is the predicate function for usergroupadmin builders.
type UserGroupAdmin func(*sql.Selector)

// UserGroupUser is the predicate function for usergroupuser builders.
type UserGroupUser func(*sql.Selector)

// UserIdentity is the predicate function for useridentity builders.
type UserIdentity func(*sql.Selector)

// UserLoginHistory is the predicate function for userloginhistory builders.
type UserLoginHistory func(*sql.Selector)

// Workspace is the predicate function for workspace builders.
type Workspace func(*sql.Selector)

// WorkspaceFile is the predicate function for workspacefile builders.
type WorkspaceFile func(*sql.Selector)
